name: Android CI

on:
  push:
    branches: [ main ]

jobs:

  gradleValidation:
    name: Gradle Wrapper
    runs-on: macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  android:
    name: Android
    needs: gradleValidation
    runs-on: macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Fix gradlew permission
        run: chmod +x gradlew
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Assemble
        run: ./gradlew assembleDebug bundleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab

      - name: Lint
        run: ./gradlew lint --stacktrace
      - name: Archive Lint reports
        uses: actions/upload-artifact@v2
        with:
          name: lint
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml

      - name: Unit tests
        run: ./gradlew test --stacktrace
      - name: Archive Unit tests reports
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests
          path: |
            app/build/reports/tests/
            app/build/test-results/test*UnitTest/TEST*.xml

      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: aosp_atd
          arch: x86
          channel: canary
          script: ./gradlew connectedCheck
      - name: Archive Instrumented tests reports
        uses: actions/upload-artifact@v2
        with:
          name: instrumented-tests
          path: |
            app/build/outputs/androidTest-results/connected/test-result.pb
            app/build/outputs/androidTest-results/managedDevice/test-result.pb
